name:                image
version:             0.1.0.0
github:              "/image"
license:             BSD3
author:              "Adi Maini, Anton Nekhai"
maintainer:          "adimaini@vt.edu"
copyright:           "2020 Adi Maini & Anton Nekhai"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/image#readme>

dependencies:
- base >= 4.7 && < 5

- JuicyPixels >= 3.3.5
- filepath >= 1.4.2.1
- hip
- matrix 
- vector >= 0.12.1.2
- containers >= 0.6.2.1
- regex-tdfa >= 1.3.1.0
- directory >= 1.3.6.1
- random-shuffle >= 0.0.4

library:
  source-dirs: src

executables:
  image-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image

tests:
  image-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - image
